name: Build and Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@main
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Restore Quartz plugins
        run: npx quartz plugin restore

      - name: Build Quartz
        run: npx quartz build
